### ISSUE TITLE
[DEP0128] DeprecationWarning: Invalid 'main' field

### ISSUE THREAD

**Issue by Afondevi** [SoftwareBrothers/adminjs-sequelizejs#86]
(node:20) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/src/app/node_modules/@admin-bro/sequelize/package.json' of 'build/index.js'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:364:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/usr/src/app/dist/admin/AdminBro.js:9:37)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/usr/src/app/dist/server.js:54:31)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/usr/src/app/dist/index.js:23:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

**Comment by dziraf** [comment]
this should be fixed
